### PR TITLE
Fix race condition on shutdown event

### LINKED ISSUE #28: Race condition on shutdown
**Mpv.NET (lib) Version** current master

**Describe the bug**
When the shutdown event is triggered by MPV, the eventLoopTask gets the event and calls MpvEvents::HandleShutdown().

Here is the first issue. It calls functions.TerminateDestroy(handle) which destroys the handle. And it then calls eventLoop::Stop() which tries to call the Functions.Wakeup(mpvHandle) which fails since the handle is destroyed.

The main issue though is that this is all done in the eventLoopTask. So even if we switch the calls to functions.TerminateDestroy(handle) and eventLoop::Stop() i the MpvEvent::HandleShutdown() function, the Functions.Wakeup(mpvHandle) call is followed by waiting for the eventLookTask to finish. So it is waiting for itself to finish and deadlocking.

**To Reproduce**
```csharp
using (var mpv = new Mpv.NET.API.Mpv(libPath))
{
    mpv.Command("loadfile", filePath);
    mpv.EndFile += (s, a) => mpv.Command("quit");
    while (mpv.EventLoop.IsRunning)
    {
    }
}
```
Though please keep in mind, I'm still quite unsure how I'm supposed to handle the EventLoop. Advice is welcome.

**Expected behavior**
I would expect the EventLoop to stop when the "quit" command is called. Thus leaving the loop and disposing the mpv object when it goes out of the using scope.

**Additional context**
I'm currently investigating various issues regarding memory leaks and handle leaks.
I will try to implement a very simplified version of an MPV wrapper in c#. At least to get more familiar with the libmpv. Which is not very well documented in my opinion.
Hopefully I can find a solution for the race condition and the handle leak. If it isn't an issue in the libmpv itself. Not sure how stable the stable releases of libmpv actually are.

As a side note: I'm trying to read the duration of a couple hundred thousand videos using the above code. I use the mpv.FileLoaded event to know when the duration property is accessable and then I try to quit. Which I previously did by existing the loop and disposing the object. But this seems to keep 4 handles open. After getting the duration of 1053 files, I had about 4k handles open, crashing the application.
Now I tried to properly "unload" the video before exiting. But the only way to do something like that is the "quit" command it seems.

### PR DESCRIPTION
**Pull request by SebastianBecker2**
Closes #28 
When the event loop receives the shutdown event the event loop task
tried to TerminateDestroy the mpv handle and subsequently wait for
itself to finish.
Instead of calling TerminateDestroy in the shutdown event handler, it
relies on the Mpv::Dispose(bool) function to do so.
And the event loops stop functions checks if it's called by it's own
thread to avoid waiting on itself.

### CODE REVIEW

**Comment by SebastianBecker2** [comment]
As a side note: I think MvpEventLoop.IsRunning is a candidate for the volatile keyword.
But maybe there is a reason it isn't volatile.
Personally, I try to wrap those situations in CancellationTokens. Just to be sure.

**Comment by hudec117** [comment]
@SebastianBecker2 thank you for the improvements! I didn't have a reason for it **not** to be marked as volatile so if you believe there's a better way of doing it, I will happily accept it. Let me know if you want to include it in this pull request or another.

**Comment by SebastianBecker2** [comment]
I added the volatile keyword. IsRunning is now a full property. With isRunning as the underlying volatile field.

**Comment by hudec117** [comment]
Thank you for the fix, I'll look to put out another version onto Nuget in the next week.

**Pull request merged**
